export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_INVALID_PASSWORD = 'LOGIN_INVALID_PASSWORD';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_NOT_FOUND = 'LOGIN_NOT_FOUND';
export const LOGIN_FETCH_USER = 'LOGIN_FETCH_USER';
export const LOGIN_REFRESH_JWTTOKEN = 'LOGIN_REFRESH_JWTTOKEN';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const SESSION_EXPIRED = 'SESSION_EXPIRED'
export const REFRESH_TRIGGERED = 'REFRESH_TRIGGERED'
export const LOGOUT = 'LOGOUT';

