export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_INVALID_PASSWORD = 'LOGIN_INVALID_PASSWORD';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_NOT_FOUND = 'LOGIN_NOT_FOUND'